### ISSUE TITLE
DeutscheBankPsuPasswordEncryptionService throws IOException

### ISSUE THREAD

**Issue by valb3r** [adorsys/xs2a-adapter#577]
When initializing Xs2a-adapter, the following exception is thrown:
```
java.util.ServiceConfigurationError: de.adorsys.xs2a.adapter.api.PaymentInitiationServiceProvider: Provider de.adorsys.xs2a.adapter.deutschebank.DeutscheBankServiceProvider could not be instantiated
	at java.base/java.util.ServiceLoader.fail(ServiceLoader.java:582)
	at java.base/java.util.ServiceLoader$ProviderImpl.newInstance(ServiceLoader.java:804)
	at java.base/java.util.ServiceLoader$ProviderImpl.get(ServiceLoader.java:722)
	at java.base/java.util.ServiceLoader$3.next(ServiceLoader.java:1395)
	at java.base/java.util.Spliterators$IteratorSpliterator.tryAdvance(Spliterators.java:1812)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:127)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:502)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:543)
	at de.adorsys.xs2a.adapter.serviceloader.AdapterServiceLoader.getServiceProvider(AdapterServiceLoader.java:125)
	at de.adorsys.xs2a.adapter.serviceloader.AdapterServiceLoader.getPaymentInitiationService(AdapterServiceLoader.java:138)
	at de.adorsys.xs2a.adapter.serviceloader.PaymentInitiationServiceImpl.getPaymentInitiationService(PaymentInitiationServiceImpl.java:27)
	at de.adorsys.xs2a.adapter.serviceloader.PaymentInitiationServiceImpl.initiatePayment(PaymentInitiationServiceImpl.java:22)
	at de.adorsys.opba.protocol.xs2a.service.xs2a.payment.CreateSinglePaymentService.initiatePayment(CreateSinglePaymentService.java:79)
	at de.adorsys.opba.protocol.xs2a.service.xs2a.payment.CreateSinglePaymentService.lambda$doRealExecution$0(CreateSinglePaymentService.java:65)
	at de.adorsys.opba.protocol.xs2a.service.xs2a.consent.CreateConsentOrPaymentPossibleErrorHandler.tryCreateAndHandleErrors(CreateConsentOrPaymentPossibleErrorHandler.java:38)
	at de.adorsys.opba.protocol.xs2a.service.xs2a.payment.CreateSinglePaymentService.doRealExecution(CreateSinglePaymentService.java:65)
	at de.adorsys.opba.protocol.xs2a.service.xs2a.payment.CreateSinglePaymentService.doRealExecution(CreateSinglePaymentService.java:36)
	at de.adorsys.opba.protocol.bpmnshared.service.exec.ValidatedExecution.execute(ValidatedExecution.java:34)
	at de.adorsys.opba.protocol.bpmnshared.service.exec.ValidatedExecution$$FastClassBySpringCGLIB$$157556d0.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:769)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:366)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:99)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:689)
	at de.adorsys.opba.protocol.xs2a.service.xs2a.payment.CreateSinglePaymentService$$EnhancerBySpringCGLIB$$149710a0.execute(<generated>)
	at org.flowable.engine.impl.delegate.invocation.JavaDelegateInvocation.invoke(JavaDelegateInvocation.java:35)
	at org.flowable.engine.impl.delegate.invocation.DelegateInvocation.proceed(DelegateInvocation.java:35)
	at org.flowable.engine.impl.delegate.invocation.DefaultDelegateInterceptor.handleInvocation(DefaultDelegateInterceptor.java:26)
	at org.flowable.engine.impl.bpmn.behavior.ServiceTaskDelegateExpressionActivityBehavior.execute(ServiceTaskDelegateExpressionActivityBehavior.java:111)
	at org.flowable.engine.impl.agenda.ContinueProcessOperation.executeActivityBehavior(ContinueProcessOperation.java:275)
	at org.flowable.engine.impl.agenda.ContinueProcessOperation.executeSynchronous(ContinueProcessOperation.java:159)
	at org.flowable.engine.impl.agenda.ContinueProcessOperation.continueThroughFlowNode(ContinueProcessOperation.java:114)
	at org.flowable.engine.impl.agenda.ContinueProcessOperation.run(ContinueProcessOperation.java:78)
	at org.flowable.engine.impl.interceptor.CommandInvoker.executeOperation(CommandInvoker.java:88)
	at org.flowable.engine.impl.interceptor.CommandInvoker.executeOperations(CommandInvoker.java:72)
	at org.flowable.engine.impl.interceptor.CommandInvoker.execute(CommandInvoker.java:56)
	at org.flowable.engine.impl.interceptor.BpmnOverrideContextInterceptor.execute(BpmnOverrideContextInterceptor.java:25)
	at org.flowable.common.engine.impl.interceptor.TransactionContextInterceptor.execute(TransactionContextInterceptor.java:53)
	at org.flowable.common.engine.impl.interceptor.CommandContextInterceptor.execute(CommandContextInterceptor.java:72)
	at org.flowable.common.spring.SpringTransactionInterceptor.lambda$execute$0(SpringTransactionInterceptor.java:56)
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:140)
	at org.flowable.common.spring.SpringTransactionInterceptor.execute(SpringTransactionInterceptor.java:56)
	at org.flowable.common.engine.impl.interceptor.LogInterceptor.execute(LogInterceptor.java:30)
	at org.flowable.common.engine.impl.cfg.CommandExecutorImpl.execute(CommandExecutorImpl.java:56)
	at org.flowable.common.engine.impl.cfg.CommandExecutorImpl.execute(CommandExecutorImpl.java:51)
	at org.flowable.job.service.impl.asyncexecutor.ExecuteAsyncRunnable.executeJob(ExecuteAsyncRunnable.java:128)
	at org.flowable.job.service.impl.asyncexecutor.ExecuteAsyncRunnable.run(ExecuteAsyncRunnable.java:116)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: de.adorsys.xs2a.adapter.api.exception.PsuPasswordEncodingException: Exception during Deutsche bank adapter PSU password encryption
	at de.adorsys.xs2a.adapter.deutschebank.DeutscheBankPsuPasswordEncryptionService.init(DeutscheBankPsuPasswordEncryptionService.java:90)
	at de.adorsys.xs2a.adapter.deutschebank.DeutscheBankPsuPasswordEncryptionService.<init>(DeutscheBankPsuPasswordEncryptionService.java:44)
	at de.adorsys.xs2a.adapter.deutschebank.DeutscheBankPsuPasswordEncryptionService.getInstance(DeutscheBankPsuPasswordEncryptionService.java:37)
	at de.adorsys.xs2a.adapter.deutschebank.DeutscheBankServiceProvider.<init>(DeutscheBankServiceProvider.java:29)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at java.base/java.util.ServiceLoader$ProviderImpl.newInstance(ServiceLoader.java:780)
	... 56 common frames omitted
Caused by: org.bouncycastle.jcajce.provider.asymmetric.x509.CertificateFactory$ExCertificateException: parsing issue: malformed PEM data: no header found
	at org.bouncycastle.jcajce.provider.asymmetric.x509.CertificateFactory.engineGenerateCertificate(Unknown Source)
	at org.bouncycastle.jcajce.provider.asymmetric.x509.CertificateFactory.engineGenerateCertificates(Unknown Source)
	at de.adorsys.xs2a.adapter.deutschebank.DeutscheBankPsuPasswordEncryptionService.init(DeutscheBankPsuPasswordEncryptionService.java:71)
	... 64 common frames omitted
Caused by: java.io.IOException: malformed PEM data: no header found
	at org.bouncycastle.jcajce.provider.asymmetric.x509.PEMUtil.readPEMObject(Unknown Source)
	at org.bouncycastle.jcajce.provider.asymmetric.x509.CertificateFactory.readPEMCertificate(Unknown Source)
	... 67 common frames omitted
```

Xs2a-adapter version `0.1.8`

**Comment by berezkin88** [comment]
Fixed. The fix is available via GitHub packages or with the next release `0.1.10`
